namespace RT3MapEditor
{
	// Token: 0x02000010 RID: 16
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class BootScreenDialog : global::System.Windows.Forms.Form
	{
		// Token: 0x060001D0 RID: 464 RVA: 0x0013E72C File Offset: 0x0013D72C
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060001D1 RID: 465 RVA: 0x0013E77C File Offset: 0x0013D77C
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::RT3MapEditor.BootScreenDialog));
			this.TableLayoutPanel1 = new global::System.Windows.Forms.TableLayoutPanel();
			this.OK_Button = new global::System.Windows.Forms.Button();
			this.Cancel_Button = new global::System.Windows.Forms.Button();
			this.DriveListView = new global::System.Windows.Forms.ListView();
			this.Refresh_Button = new global::System.Windows.Forms.Button();
			this.USBGroupBox = new global::System.Windows.Forms.GroupBox();
			this.USB_RadioButton = new global::System.Windows.Forms.RadioButton();
			this.CD_ROM_RadioButton = new global::System.Windows.Forms.RadioButton();
			this.BSGroupBox = new global::System.Windows.Forms.GroupBox();
			this.Preview_PictureBox = new global::System.Windows.Forms.PictureBox();
			this.Path_TextBox = new global::System.Windows.Forms.TextBox();
			this.RTx_RadioButton = new global::System.Windows.Forms.RadioButton();
			this.Browse_Button = new global::System.Windows.Forms.Button();
			this.Custom_RadioButton = new global::System.Windows.Forms.RadioButton();
			this.Preview_Button = new global::System.Windows.Forms.Button();
			this.PC_RadioButton = new global::System.Windows.Forms.RadioButton();
			this.Lan_RadioButton = new global::System.Windows.Forms.RadioButton();
			this.Fiat_RadioButton = new global::System.Windows.Forms.RadioButton();
			this.Cit_RadioButton = new global::System.Windows.Forms.RadioButton();
			this.Peu_RadioButton = new global::System.Windows.Forms.RadioButton();
			this.MM_RadioButton = new global::System.Windows.Forms.RadioButton();
			this.HelpProvider1 = new global::System.Windows.Forms.HelpProvider();
			this.TableLayoutPanel1.SuspendLayout();
			this.USBGroupBox.SuspendLayout();
			this.BSGroupBox.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Preview_PictureBox).BeginInit();
			this.SuspendLayout();
			this.TableLayoutPanel1.AccessibleDescription = null;
			this.TableLayoutPanel1.AccessibleName = null;
			componentResourceManager.ApplyResources(this.TableLayoutPanel1, "TableLayoutPanel1");
			this.TableLayoutPanel1.BackgroundImage = null;
			this.TableLayoutPanel1.Controls.Add(this.OK_Button, 0, 0);
			this.TableLayoutPanel1.Controls.Add(this.Cancel_Button, 1, 0);
			this.TableLayoutPanel1.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.TableLayoutPanel1, null);
			this.HelpProvider1.SetHelpNavigator(this.TableLayoutPanel1, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("TableLayoutPanel1.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.TableLayoutPanel1, null);
			this.TableLayoutPanel1.Name = "TableLayoutPanel1";
			this.HelpProvider1.SetShowHelp(this.TableLayoutPanel1, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("TableLayoutPanel1.ShowHelp")));
			this.OK_Button.AccessibleDescription = null;
			this.OK_Button.AccessibleName = null;
			componentResourceManager.ApplyResources(this.OK_Button, "OK_Button");
			this.OK_Button.BackgroundImage = null;
			this.OK_Button.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.OK_Button, null);
			this.HelpProvider1.SetHelpNavigator(this.OK_Button, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("OK_Button.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.OK_Button, null);
			this.OK_Button.Name = "OK_Button";
			this.HelpProvider1.SetShowHelp(this.OK_Button, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("OK_Button.ShowHelp")));
			this.Cancel_Button.AccessibleDescription = null;
			this.Cancel_Button.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Cancel_Button, "Cancel_Button");
			this.Cancel_Button.BackgroundImage = null;
			this.Cancel_Button.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			this.Cancel_Button.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Cancel_Button, null);
			this.HelpProvider1.SetHelpNavigator(this.Cancel_Button, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Cancel_Button.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Cancel_Button, null);
			this.Cancel_Button.Name = "Cancel_Button";
			this.HelpProvider1.SetShowHelp(this.Cancel_Button, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Cancel_Button.ShowHelp")));
			this.DriveListView.AccessibleDescription = null;
			this.DriveListView.AccessibleName = null;
			componentResourceManager.ApplyResources(this.DriveListView, "DriveListView");
			this.DriveListView.BackgroundImage = null;
			this.DriveListView.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.DriveListView, null);
			this.HelpProvider1.SetHelpNavigator(this.DriveListView, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("DriveListView.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.DriveListView, null);
			this.DriveListView.Name = "DriveListView";
			this.HelpProvider1.SetShowHelp(this.DriveListView, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("DriveListView.ShowHelp")));
			this.DriveListView.UseCompatibleStateImageBehavior = false;
			this.Refresh_Button.AccessibleDescription = null;
			this.Refresh_Button.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Refresh_Button, "Refresh_Button");
			this.Refresh_Button.BackgroundImage = null;
			this.Refresh_Button.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Refresh_Button, null);
			this.HelpProvider1.SetHelpNavigator(this.Refresh_Button, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Refresh_Button.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Refresh_Button, null);
			this.Refresh_Button.Name = "Refresh_Button";
			this.HelpProvider1.SetShowHelp(this.Refresh_Button, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Refresh_Button.ShowHelp")));
			this.Refresh_Button.UseVisualStyleBackColor = true;
			this.USBGroupBox.AccessibleDescription = null;
			this.USBGroupBox.AccessibleName = null;
			componentResourceManager.ApplyResources(this.USBGroupBox, "USBGroupBox");
			this.USBGroupBox.BackgroundImage = null;
			this.USBGroupBox.Controls.Add(this.USB_RadioButton);
			this.USBGroupBox.Controls.Add(this.CD_ROM_RadioButton);
			this.USBGroupBox.Controls.Add(this.DriveListView);
			this.USBGroupBox.Controls.Add(this.Refresh_Button);
			this.USBGroupBox.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.USBGroupBox, null);
			this.HelpProvider1.SetHelpNavigator(this.USBGroupBox, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("USBGroupBox.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.USBGroupBox, null);
			this.USBGroupBox.Name = "USBGroupBox";
			this.HelpProvider1.SetShowHelp(this.USBGroupBox, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("USBGroupBox.ShowHelp")));
			this.USBGroupBox.TabStop = false;
			this.USB_RadioButton.AccessibleDescription = null;
			this.USB_RadioButton.AccessibleName = null;
			componentResourceManager.ApplyResources(this.USB_RadioButton, "USB_RadioButton");
			this.USB_RadioButton.BackgroundImage = null;
			this.USB_RadioButton.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.USB_RadioButton, null);
			this.HelpProvider1.SetHelpNavigator(this.USB_RadioButton, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("USB_RadioButton.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.USB_RadioButton, null);
			this.USB_RadioButton.Name = "USB_RadioButton";
			this.HelpProvider1.SetShowHelp(this.USB_RadioButton, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("USB_RadioButton.ShowHelp")));
			this.USB_RadioButton.TabStop = true;
			this.USB_RadioButton.UseVisualStyleBackColor = true;
			this.CD_ROM_RadioButton.AccessibleDescription = null;
			this.CD_ROM_RadioButton.AccessibleName = null;
			componentResourceManager.ApplyResources(this.CD_ROM_RadioButton, "CD_ROM_RadioButton");
			this.CD_ROM_RadioButton.BackgroundImage = null;
			this.CD_ROM_RadioButton.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.CD_ROM_RadioButton, null);
			this.HelpProvider1.SetHelpNavigator(this.CD_ROM_RadioButton, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("CD_ROM_RadioButton.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.CD_ROM_RadioButton, null);
			this.CD_ROM_RadioButton.Name = "CD_ROM_RadioButton";
			this.HelpProvider1.SetShowHelp(this.CD_ROM_RadioButton, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("CD_ROM_RadioButton.ShowHelp")));
			this.CD_ROM_RadioButton.TabStop = true;
			this.CD_ROM_RadioButton.UseVisualStyleBackColor = true;
			this.BSGroupBox.AccessibleDescription = null;
			this.BSGroupBox.AccessibleName = null;
			componentResourceManager.ApplyResources(this.BSGroupBox, "BSGroupBox");
			this.BSGroupBox.BackgroundImage = null;
			this.BSGroupBox.Controls.Add(this.Preview_PictureBox);
			this.BSGroupBox.Controls.Add(this.Path_TextBox);
			this.BSGroupBox.Controls.Add(this.RTx_RadioButton);
			this.BSGroupBox.Controls.Add(this.Browse_Button);
			this.BSGroupBox.Controls.Add(this.Custom_RadioButton);
			this.BSGroupBox.Controls.Add(this.Preview_Button);
			this.BSGroupBox.Controls.Add(this.PC_RadioButton);
			this.BSGroupBox.Controls.Add(this.Lan_RadioButton);
			this.BSGroupBox.Controls.Add(this.Fiat_RadioButton);
			this.BSGroupBox.Controls.Add(this.Cit_RadioButton);
			this.BSGroupBox.Controls.Add(this.Peu_RadioButton);
			this.BSGroupBox.Controls.Add(this.MM_RadioButton);
			this.BSGroupBox.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.BSGroupBox, null);
			this.HelpProvider1.SetHelpNavigator(this.BSGroupBox, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("BSGroupBox.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.BSGroupBox, null);
			this.BSGroupBox.Name = "BSGroupBox";
			this.HelpProvider1.SetShowHelp(this.BSGroupBox, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("BSGroupBox.ShowHelp")));
			this.BSGroupBox.TabStop = false;
			this.Preview_PictureBox.AccessibleDescription = null;
			this.Preview_PictureBox.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Preview_PictureBox, "Preview_PictureBox");
			this.Preview_PictureBox.BackgroundImage = null;
			this.Preview_PictureBox.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Preview_PictureBox, null);
			this.HelpProvider1.SetHelpNavigator(this.Preview_PictureBox, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Preview_PictureBox.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Preview_PictureBox, null);
			this.Preview_PictureBox.ImageLocation = null;
			this.Preview_PictureBox.Name = "Preview_PictureBox";
			this.HelpProvider1.SetShowHelp(this.Preview_PictureBox, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Preview_PictureBox.ShowHelp")));
			this.Preview_PictureBox.TabStop = false;
			this.Path_TextBox.AccessibleDescription = null;
			this.Path_TextBox.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Path_TextBox, "Path_TextBox");
			this.Path_TextBox.BackgroundImage = null;
			this.Path_TextBox.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Path_TextBox, null);
			this.HelpProvider1.SetHelpNavigator(this.Path_TextBox, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Path_TextBox.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Path_TextBox, null);
			this.Path_TextBox.Name = "Path_TextBox";
			this.HelpProvider1.SetShowHelp(this.Path_TextBox, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Path_TextBox.ShowHelp")));
			this.RTx_RadioButton.AccessibleDescription = null;
			this.RTx_RadioButton.AccessibleName = null;
			componentResourceManager.ApplyResources(this.RTx_RadioButton, "RTx_RadioButton");
			this.RTx_RadioButton.BackgroundImage = null;
			this.RTx_RadioButton.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.RTx_RadioButton, null);
			this.HelpProvider1.SetHelpNavigator(this.RTx_RadioButton, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("RTx_RadioButton.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.RTx_RadioButton, null);
			this.RTx_RadioButton.Name = "RTx_RadioButton";
			this.HelpProvider1.SetShowHelp(this.RTx_RadioButton, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("RTx_RadioButton.ShowHelp")));
			this.RTx_RadioButton.TabStop = true;
			this.RTx_RadioButton.UseVisualStyleBackColor = true;
			this.Browse_Button.AccessibleDescription = null;
			this.Browse_Button.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Browse_Button, "Browse_Button");
			this.Browse_Button.BackgroundImage = null;
			this.Browse_Button.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Browse_Button, null);
			this.HelpProvider1.SetHelpNavigator(this.Browse_Button, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Browse_Button.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Browse_Button, null);
			this.Browse_Button.Name = "Browse_Button";
			this.HelpProvider1.SetShowHelp(this.Browse_Button, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Browse_Button.ShowHelp")));
			this.Browse_Button.UseVisualStyleBackColor = true;
			this.Custom_RadioButton.AccessibleDescription = null;
			this.Custom_RadioButton.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Custom_RadioButton, "Custom_RadioButton");
			this.Custom_RadioButton.BackgroundImage = null;
			this.Custom_RadioButton.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Custom_RadioButton, null);
			this.HelpProvider1.SetHelpNavigator(this.Custom_RadioButton, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Custom_RadioButton.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Custom_RadioButton, null);
			this.Custom_RadioButton.Name = "Custom_RadioButton";
			this.HelpProvider1.SetShowHelp(this.Custom_RadioButton, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Custom_RadioButton.ShowHelp")));
			this.Custom_RadioButton.TabStop = true;
			this.Custom_RadioButton.UseVisualStyleBackColor = true;
			this.Preview_Button.AccessibleDescription = null;
			this.Preview_Button.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Preview_Button, "Preview_Button");
			this.Preview_Button.BackgroundImage = null;
			this.Preview_Button.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Preview_Button, null);
			this.HelpProvider1.SetHelpNavigator(this.Preview_Button, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Preview_Button.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Preview_Button, null);
			this.Preview_Button.Name = "Preview_Button";
			this.HelpProvider1.SetShowHelp(this.Preview_Button, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Preview_Button.ShowHelp")));
			this.Preview_Button.UseVisualStyleBackColor = true;
			this.PC_RadioButton.AccessibleDescription = null;
			this.PC_RadioButton.AccessibleName = null;
			componentResourceManager.ApplyResources(this.PC_RadioButton, "PC_RadioButton");
			this.PC_RadioButton.BackgroundImage = null;
			this.PC_RadioButton.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.PC_RadioButton, null);
			this.HelpProvider1.SetHelpNavigator(this.PC_RadioButton, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("PC_RadioButton.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.PC_RadioButton, null);
			this.PC_RadioButton.Name = "PC_RadioButton";
			this.HelpProvider1.SetShowHelp(this.PC_RadioButton, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("PC_RadioButton.ShowHelp")));
			this.PC_RadioButton.TabStop = true;
			this.PC_RadioButton.UseVisualStyleBackColor = true;
			this.Lan_RadioButton.AccessibleDescription = null;
			this.Lan_RadioButton.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Lan_RadioButton, "Lan_RadioButton");
			this.Lan_RadioButton.BackgroundImage = null;
			this.Lan_RadioButton.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Lan_RadioButton, null);
			this.HelpProvider1.SetHelpNavigator(this.Lan_RadioButton, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Lan_RadioButton.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Lan_RadioButton, null);
			this.Lan_RadioButton.Name = "Lan_RadioButton";
			this.HelpProvider1.SetShowHelp(this.Lan_RadioButton, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Lan_RadioButton.ShowHelp")));
			this.Lan_RadioButton.TabStop = true;
			this.Lan_RadioButton.UseVisualStyleBackColor = true;
			this.Fiat_RadioButton.AccessibleDescription = null;
			this.Fiat_RadioButton.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Fiat_RadioButton, "Fiat_RadioButton");
			this.Fiat_RadioButton.BackgroundImage = null;
			this.Fiat_RadioButton.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Fiat_RadioButton, null);
			this.HelpProvider1.SetHelpNavigator(this.Fiat_RadioButton, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Fiat_RadioButton.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Fiat_RadioButton, null);
			this.Fiat_RadioButton.Name = "Fiat_RadioButton";
			this.HelpProvider1.SetShowHelp(this.Fiat_RadioButton, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Fiat_RadioButton.ShowHelp")));
			this.Fiat_RadioButton.TabStop = true;
			this.Fiat_RadioButton.UseVisualStyleBackColor = true;
			this.Cit_RadioButton.AccessibleDescription = null;
			this.Cit_RadioButton.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Cit_RadioButton, "Cit_RadioButton");
			this.Cit_RadioButton.BackgroundImage = null;
			this.Cit_RadioButton.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Cit_RadioButton, null);
			this.HelpProvider1.SetHelpNavigator(this.Cit_RadioButton, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Cit_RadioButton.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Cit_RadioButton, null);
			this.Cit_RadioButton.Name = "Cit_RadioButton";
			this.HelpProvider1.SetShowHelp(this.Cit_RadioButton, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Cit_RadioButton.ShowHelp")));
			this.Cit_RadioButton.TabStop = true;
			this.Cit_RadioButton.UseVisualStyleBackColor = true;
			this.Peu_RadioButton.AccessibleDescription = null;
			this.Peu_RadioButton.AccessibleName = null;
			componentResourceManager.ApplyResources(this.Peu_RadioButton, "Peu_RadioButton");
			this.Peu_RadioButton.BackgroundImage = null;
			this.Peu_RadioButton.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.Peu_RadioButton, null);
			this.HelpProvider1.SetHelpNavigator(this.Peu_RadioButton, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("Peu_RadioButton.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.Peu_RadioButton, null);
			this.Peu_RadioButton.Name = "Peu_RadioButton";
			this.HelpProvider1.SetShowHelp(this.Peu_RadioButton, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("Peu_RadioButton.ShowHelp")));
			this.Peu_RadioButton.TabStop = true;
			this.Peu_RadioButton.UseVisualStyleBackColor = true;
			this.MM_RadioButton.AccessibleDescription = null;
			this.MM_RadioButton.AccessibleName = null;
			componentResourceManager.ApplyResources(this.MM_RadioButton, "MM_RadioButton");
			this.MM_RadioButton.BackgroundImage = null;
			this.MM_RadioButton.Font = null;
			this.HelpProvider1.SetHelpKeyword(this.MM_RadioButton, null);
			this.HelpProvider1.SetHelpNavigator(this.MM_RadioButton, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("MM_RadioButton.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this.MM_RadioButton, null);
			this.MM_RadioButton.Name = "MM_RadioButton";
			this.HelpProvider1.SetShowHelp(this.MM_RadioButton, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("MM_RadioButton.ShowHelp")));
			this.MM_RadioButton.TabStop = true;
			this.MM_RadioButton.UseVisualStyleBackColor = true;
			this.HelpProvider1.HelpNamespace = null;
			this.AcceptButton = this.OK_Button;
			this.AccessibleDescription = null;
			this.AccessibleName = null;
			componentResourceManager.ApplyResources(this, "$this");
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackgroundImage = null;
			this.CancelButton = this.Cancel_Button;
			this.Controls.Add(this.USBGroupBox);
			this.Controls.Add(this.TableLayoutPanel1);
			this.Controls.Add(this.BSGroupBox);
			this.Font = null;
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.HelpButton = true;
			this.HelpProvider1.SetHelpKeyword(this, null);
			this.HelpProvider1.SetHelpNavigator(this, (global::System.Windows.Forms.HelpNavigator)global::Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(componentResourceManager.GetObject("$this.HelpNavigator")));
			this.HelpProvider1.SetHelpString(this, null);
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "BootScreenDialog";
			this.HelpProvider1.SetShowHelp(this, global::Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(componentResourceManager.GetObject("$this.ShowHelp")));
			this.ShowInTaskbar = false;
			this.TableLayoutPanel1.ResumeLayout(false);
			this.USBGroupBox.ResumeLayout(false);
			this.USBGroupBox.PerformLayout();
			this.BSGroupBox.ResumeLayout(false);
			this.BSGroupBox.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Preview_PictureBox).EndInit();
			this.ResumeLayout(false);
		}

		// Token: 0x04000103 RID: 259
		private global::System.ComponentModel.IContainer components;
	}
}
