namespace RT3MapEditor
{
	// Token: 0x02000037 RID: 55
	[global::Microsoft.VisualBasic.CompilerServices.DesignerGenerated]
	public partial class CoordConvDialog : global::System.Windows.Forms.Form
	{
		// Token: 0x060005E6 RID: 1510 RVA: 0x00155354 File Offset: 0x00154354
		[global::System.Diagnostics.DebuggerNonUserCode]
		protected override void Dispose(bool disposing)
		{
			try
			{
				bool flag = disposing && this.components != null;
				if (flag)
				{
					this.components.Dispose();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}

		// Token: 0x060005E7 RID: 1511 RVA: 0x001553A4 File Offset: 0x001543A4
		[global::System.Diagnostics.DebuggerStepThrough]
		private void InitializeComponent()
		{
			this.TableLayoutPanel1 = new global::System.Windows.Forms.TableLayoutPanel();
			this.OK_Button = new global::System.Windows.Forms.Button();
			this.Cancel_Button = new global::System.Windows.Forms.Button();
			this.LSI_NumericUpDown = new global::System.Windows.Forms.NumericUpDown();
			this.LabelLSI = new global::System.Windows.Forms.Label();
			this.LabelMSI = new global::System.Windows.Forms.Label();
			this.MSI_NumericUpDown = new global::System.Windows.Forms.NumericUpDown();
			this.LabelSSI = new global::System.Windows.Forms.Label();
			this.SSI_NumericUpDown = new global::System.Windows.Forms.NumericUpDown();
			this.LabelXI = new global::System.Windows.Forms.Label();
			this.XI_NumericUpDown = new global::System.Windows.Forms.NumericUpDown();
			this.LabelYI = new global::System.Windows.Forms.Label();
			this.YI_NumericUpDown = new global::System.Windows.Forms.NumericUpDown();
			this.CellCalc_Button = new global::System.Windows.Forms.Button();
			this.LabelEO = new global::System.Windows.Forms.Label();
			this.EO_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelNO = new global::System.Windows.Forms.Label();
			this.NO_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelLatO = new global::System.Windows.Forms.Label();
			this.LatO_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelLonO = new global::System.Windows.Forms.Label();
			this.LonO_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelLatI = new global::System.Windows.Forms.Label();
			this.LatI_TextBox = new global::System.Windows.Forms.TextBox();
			this.Label1LonI = new global::System.Windows.Forms.Label();
			this.LonI_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelEI = new global::System.Windows.Forms.Label();
			this.EI_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelNI = new global::System.Windows.Forms.Label();
			this.NI_TextBox = new global::System.Windows.Forms.TextBox();
			this.Label14 = new global::System.Windows.Forms.Label();
			this.LatLonCalc_Button = new global::System.Windows.Forms.Button();
			this.ENCalc_Button = new global::System.Windows.Forms.Button();
			this.Label15 = new global::System.Windows.Forms.Label();
			this.LabelLSO = new global::System.Windows.Forms.Label();
			this.LSO_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelMSO = new global::System.Windows.Forms.Label();
			this.LabelSSO = new global::System.Windows.Forms.Label();
			this.MSO_TextBox = new global::System.Windows.Forms.TextBox();
			this.SSO_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelXO = new global::System.Windows.Forms.Label();
			this.XO_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelYO = new global::System.Windows.Forms.Label();
			this.YO_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelCellO = new global::System.Windows.Forms.Label();
			this.Cell0_TextBox = new global::System.Windows.Forms.TextBox();
			this.AscO_TextBox = new global::System.Windows.Forms.TextBox();
			this.LabelAsc = new global::System.Windows.Forms.Label();
			this.TableLayoutPanel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.LSI_NumericUpDown).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.MSI_NumericUpDown).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.SSI_NumericUpDown).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.XI_NumericUpDown).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.YI_NumericUpDown).BeginInit();
			this.SuspendLayout();
			this.TableLayoutPanel1.Anchor = (global::System.Windows.Forms.AnchorStyles.Bottom | global::System.Windows.Forms.AnchorStyles.Right);
			this.TableLayoutPanel1.ColumnCount = 2;
			this.TableLayoutPanel1.ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			this.TableLayoutPanel1.ColumnStyles.Add(new global::System.Windows.Forms.ColumnStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			this.TableLayoutPanel1.Controls.Add(this.OK_Button, 0, 0);
			this.TableLayoutPanel1.Controls.Add(this.Cancel_Button, 1, 0);
			global::System.Windows.Forms.Control tableLayoutPanel = this.TableLayoutPanel1;
			global::System.Drawing.Point location = new global::System.Drawing.Point(336, 320);
			tableLayoutPanel.Location = location;
			this.TableLayoutPanel1.Name = "TableLayoutPanel1";
			this.TableLayoutPanel1.RowCount = 1;
			this.TableLayoutPanel1.RowStyles.Add(new global::System.Windows.Forms.RowStyle(global::System.Windows.Forms.SizeType.Percent, 50f));
			global::System.Windows.Forms.Control tableLayoutPanel2 = this.TableLayoutPanel1;
			global::System.Drawing.Size size = new global::System.Drawing.Size(146, 29);
			tableLayoutPanel2.Size = size;
			this.TableLayoutPanel1.TabIndex = 0;
			this.OK_Button.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			global::System.Windows.Forms.Control ok_Button = this.OK_Button;
			location = new global::System.Drawing.Point(3, 3);
			ok_Button.Location = location;
			this.OK_Button.Name = "OK_Button";
			global::System.Windows.Forms.Control ok_Button2 = this.OK_Button;
			size = new global::System.Drawing.Size(67, 23);
			ok_Button2.Size = size;
			this.OK_Button.TabIndex = 0;
			this.OK_Button.Text = "OK";
			this.Cancel_Button.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.Cancel_Button.DialogResult = global::System.Windows.Forms.DialogResult.Cancel;
			global::System.Windows.Forms.Control cancel_Button = this.Cancel_Button;
			location = new global::System.Drawing.Point(76, 3);
			cancel_Button.Location = location;
			this.Cancel_Button.Name = "Cancel_Button";
			global::System.Windows.Forms.Control cancel_Button2 = this.Cancel_Button;
			size = new global::System.Drawing.Size(67, 23);
			cancel_Button2.Size = size;
			this.Cancel_Button.TabIndex = 1;
			this.Cancel_Button.Text = "Cancel";
			global::System.Windows.Forms.Control lsi_NumericUpDown = this.LSI_NumericUpDown;
			location = new global::System.Drawing.Point(43, 35);
			lsi_NumericUpDown.Location = location;
			this.LSI_NumericUpDown.Name = "LSI_NumericUpDown";
			global::System.Windows.Forms.Control lsi_NumericUpDown2 = this.LSI_NumericUpDown;
			size = new global::System.Drawing.Size(38, 20);
			lsi_NumericUpDown2.Size = size;
			this.LSI_NumericUpDown.TabIndex = 2;
			this.LabelLSI.AutoSize = true;
			global::System.Windows.Forms.Control labelLSI = this.LabelLSI;
			location = new global::System.Drawing.Point(4, 37);
			labelLSI.Location = location;
			this.LabelLSI.Name = "LabelLSI";
			global::System.Windows.Forms.Control labelLSI2 = this.LabelLSI;
			size = new global::System.Drawing.Size(23, 13);
			labelLSI2.Size = size;
			this.LabelLSI.TabIndex = 1;
			this.LabelLSI.Text = "LS:";
			this.LabelMSI.AutoSize = true;
			global::System.Windows.Forms.Control labelMSI = this.LabelMSI;
			location = new global::System.Drawing.Point(83, 37);
			labelMSI.Location = location;
			this.LabelMSI.Name = "LabelMSI";
			global::System.Windows.Forms.Control labelMSI2 = this.LabelMSI;
			size = new global::System.Drawing.Size(26, 13);
			labelMSI2.Size = size;
			this.LabelMSI.TabIndex = 3;
			this.LabelMSI.Text = "MS:";
			global::System.Windows.Forms.Control msi_NumericUpDown = this.MSI_NumericUpDown;
			location = new global::System.Drawing.Point(108, 35);
			msi_NumericUpDown.Location = location;
			global::System.Windows.Forms.NumericUpDown msi_NumericUpDown2 = this.MSI_NumericUpDown;
			decimal maximum = new decimal(new int[]
			{
				255,
				0,
				0,
				0
			});
			msi_NumericUpDown2.Maximum = maximum;
			this.MSI_NumericUpDown.Name = "MSI_NumericUpDown";
			global::System.Windows.Forms.Control msi_NumericUpDown3 = this.MSI_NumericUpDown;
			size = new global::System.Drawing.Size(38, 20);
			msi_NumericUpDown3.Size = size;
			this.MSI_NumericUpDown.TabIndex = 4;
			this.LabelSSI.AutoSize = true;
			global::System.Windows.Forms.Control labelSSI = this.LabelSSI;
			location = new global::System.Drawing.Point(146, 37);
			labelSSI.Location = location;
			this.LabelSSI.Name = "LabelSSI";
			global::System.Windows.Forms.Control labelSSI2 = this.LabelSSI;
			size = new global::System.Drawing.Size(24, 13);
			labelSSI2.Size = size;
			this.LabelSSI.TabIndex = 5;
			this.LabelSSI.Text = "SS:";
			global::System.Windows.Forms.Control ssi_NumericUpDown = this.SSI_NumericUpDown;
			location = new global::System.Drawing.Point(166, 35);
			ssi_NumericUpDown.Location = location;
			global::System.Windows.Forms.NumericUpDown ssi_NumericUpDown2 = this.SSI_NumericUpDown;
			maximum = new decimal(new int[]
			{
				255,
				0,
				0,
				0
			});
			ssi_NumericUpDown2.Maximum = maximum;
			this.SSI_NumericUpDown.Name = "SSI_NumericUpDown";
			global::System.Windows.Forms.Control ssi_NumericUpDown3 = this.SSI_NumericUpDown;
			size = new global::System.Drawing.Size(38, 20);
			ssi_NumericUpDown3.Size = size;
			this.SSI_NumericUpDown.TabIndex = 6;
			this.LabelXI.AutoSize = true;
			global::System.Windows.Forms.Control labelXI = this.LabelXI;
			location = new global::System.Drawing.Point(204, 37);
			labelXI.Location = location;
			this.LabelXI.Name = "LabelXI";
			global::System.Windows.Forms.Control labelXI2 = this.LabelXI;
			size = new global::System.Drawing.Size(17, 13);
			labelXI2.Size = size;
			this.LabelXI.TabIndex = 7;
			this.LabelXI.Text = "X:";
			global::System.Windows.Forms.Control xi_NumericUpDown = this.XI_NumericUpDown;
			location = new global::System.Drawing.Point(218, 35);
			xi_NumericUpDown.Location = location;
			global::System.Windows.Forms.NumericUpDown xi_NumericUpDown2 = this.XI_NumericUpDown;
			maximum = new decimal(new int[]
			{
				999,
				0,
				0,
				0
			});
			xi_NumericUpDown2.Maximum = maximum;
			this.XI_NumericUpDown.Name = "XI_NumericUpDown";
			global::System.Windows.Forms.Control xi_NumericUpDown3 = this.XI_NumericUpDown;
			size = new global::System.Drawing.Size(38, 20);
			xi_NumericUpDown3.Size = size;
			this.XI_NumericUpDown.TabIndex = 8;
			this.LabelYI.AutoSize = true;
			global::System.Windows.Forms.Control labelYI = this.LabelYI;
			location = new global::System.Drawing.Point(262, 37);
			labelYI.Location = location;
			this.LabelYI.Name = "LabelYI";
			global::System.Windows.Forms.Control labelYI2 = this.LabelYI;
			size = new global::System.Drawing.Size(17, 13);
			labelYI2.Size = size;
			this.LabelYI.TabIndex = 9;
			this.LabelYI.Text = "Y:";
			global::System.Windows.Forms.Control yi_NumericUpDown = this.YI_NumericUpDown;
			location = new global::System.Drawing.Point(279, 35);
			yi_NumericUpDown.Location = location;
			global::System.Windows.Forms.NumericUpDown yi_NumericUpDown2 = this.YI_NumericUpDown;
			maximum = new decimal(new int[]
			{
				999,
				0,
				0,
				0
			});
			yi_NumericUpDown2.Maximum = maximum;
			this.YI_NumericUpDown.Name = "YI_NumericUpDown";
			global::System.Windows.Forms.Control yi_NumericUpDown3 = this.YI_NumericUpDown;
			size = new global::System.Drawing.Size(38, 20);
			yi_NumericUpDown3.Size = size;
			this.YI_NumericUpDown.TabIndex = 10;
			global::System.Windows.Forms.Control cellCalc_Button = this.CellCalc_Button;
			location = new global::System.Drawing.Point(328, 32);
			cellCalc_Button.Location = location;
			this.CellCalc_Button.Name = "CellCalc_Button";
			global::System.Windows.Forms.Control cellCalc_Button2 = this.CellCalc_Button;
			size = new global::System.Drawing.Size(50, 23);
			cellCalc_Button2.Size = size;
			this.CellCalc_Button.TabIndex = 11;
			this.CellCalc_Button.Text = "->";
			this.CellCalc_Button.UseVisualStyleBackColor = true;
			this.LabelEO.AutoSize = true;
			global::System.Windows.Forms.Control labelEO = this.LabelEO;
			location = new global::System.Drawing.Point(16, 202);
			labelEO.Location = location;
			this.LabelEO.Name = "LabelEO";
			global::System.Windows.Forms.Control labelEO2 = this.LabelEO;
			size = new global::System.Drawing.Size(37, 13);
			labelEO2.Size = size;
			this.LabelEO.TabIndex = 12;
			this.LabelEO.Text = "ERTx:";
			global::System.Windows.Forms.Control eo_TextBox = this.EO_TextBox;
			location = new global::System.Drawing.Point(55, 198);
			eo_TextBox.Location = location;
			this.EO_TextBox.Name = "EO_TextBox";
			this.EO_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control eo_TextBox2 = this.EO_TextBox;
			size = new global::System.Drawing.Size(59, 20);
			eo_TextBox2.Size = size;
			this.EO_TextBox.TabIndex = 13;
			this.LabelNO.AutoSize = true;
			global::System.Windows.Forms.Control labelNO = this.LabelNO;
			location = new global::System.Drawing.Point(124, 202);
			labelNO.Location = location;
			this.LabelNO.Name = "LabelNO";
			global::System.Windows.Forms.Control labelNO2 = this.LabelNO;
			size = new global::System.Drawing.Size(38, 13);
			labelNO2.Size = size;
			this.LabelNO.TabIndex = 14;
			this.LabelNO.Text = "NRTx:";
			global::System.Windows.Forms.Control no_TextBox = this.NO_TextBox;
			location = new global::System.Drawing.Point(166, 198);
			no_TextBox.Location = location;
			this.NO_TextBox.Name = "NO_TextBox";
			this.NO_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control no_TextBox2 = this.NO_TextBox;
			size = new global::System.Drawing.Size(59, 20);
			no_TextBox2.Size = size;
			this.NO_TextBox.TabIndex = 15;
			this.LabelLatO.AutoSize = true;
			global::System.Windows.Forms.Control labelLatO = this.LabelLatO;
			location = new global::System.Drawing.Point(16, 235);
			labelLatO.Location = location;
			this.LabelLatO.Name = "LabelLatO";
			global::System.Windows.Forms.Control labelLatO2 = this.LabelLatO;
			size = new global::System.Drawing.Size(25, 13);
			labelLatO2.Size = size;
			this.LabelLatO.TabIndex = 16;
			this.LabelLatO.Text = "Lat:";
			global::System.Windows.Forms.Control latO_TextBox = this.LatO_TextBox;
			location = new global::System.Drawing.Point(55, 231);
			latO_TextBox.Location = location;
			this.LatO_TextBox.Name = "LatO_TextBox";
			this.LatO_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control latO_TextBox2 = this.LatO_TextBox;
			size = new global::System.Drawing.Size(59, 20);
			latO_TextBox2.Size = size;
			this.LatO_TextBox.TabIndex = 17;
			this.LabelLonO.AutoSize = true;
			global::System.Windows.Forms.Control labelLonO = this.LabelLonO;
			location = new global::System.Drawing.Point(125, 235);
			labelLonO.Location = location;
			this.LabelLonO.Name = "LabelLonO";
			global::System.Windows.Forms.Control labelLonO2 = this.LabelLonO;
			size = new global::System.Drawing.Size(28, 13);
			labelLonO2.Size = size;
			this.LabelLonO.TabIndex = 18;
			this.LabelLonO.Text = "Lon:";
			global::System.Windows.Forms.Control lonO_TextBox = this.LonO_TextBox;
			location = new global::System.Drawing.Point(166, 231);
			lonO_TextBox.Location = location;
			this.LonO_TextBox.Name = "LonO_TextBox";
			this.LonO_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control lonO_TextBox2 = this.LonO_TextBox;
			size = new global::System.Drawing.Size(59, 20);
			lonO_TextBox2.Size = size;
			this.LonO_TextBox.TabIndex = 19;
			this.LabelLatI.AutoSize = true;
			global::System.Windows.Forms.Control labelLatI = this.LabelLatI;
			location = new global::System.Drawing.Point(3, 70);
			labelLatI.Location = location;
			this.LabelLatI.Name = "LabelLatI";
			global::System.Windows.Forms.Control labelLatI2 = this.LabelLatI;
			size = new global::System.Drawing.Size(25, 13);
			labelLatI2.Size = size;
			this.LabelLatI.TabIndex = 12;
			this.LabelLatI.Text = "Lat:";
			global::System.Windows.Forms.Control latI_TextBox = this.LatI_TextBox;
			location = new global::System.Drawing.Point(42, 66);
			latI_TextBox.Location = location;
			this.LatI_TextBox.Name = "LatI_TextBox";
			global::System.Windows.Forms.Control latI_TextBox2 = this.LatI_TextBox;
			size = new global::System.Drawing.Size(59, 20);
			latI_TextBox2.Size = size;
			this.LatI_TextBox.TabIndex = 13;
			this.Label1LonI.AutoSize = true;
			global::System.Windows.Forms.Control label1LonI = this.Label1LonI;
			location = new global::System.Drawing.Point(128, 69);
			label1LonI.Location = location;
			this.Label1LonI.Name = "Label1LonI";
			global::System.Windows.Forms.Control label1LonI2 = this.Label1LonI;
			size = new global::System.Drawing.Size(28, 13);
			label1LonI2.Size = size;
			this.Label1LonI.TabIndex = 14;
			this.Label1LonI.Text = "Lon:";
			global::System.Windows.Forms.Control lonI_TextBox = this.LonI_TextBox;
			location = new global::System.Drawing.Point(166, 67);
			lonI_TextBox.Location = location;
			this.LonI_TextBox.Name = "LonI_TextBox";
			global::System.Windows.Forms.Control lonI_TextBox2 = this.LonI_TextBox;
			size = new global::System.Drawing.Size(59, 20);
			lonI_TextBox2.Size = size;
			this.LonI_TextBox.TabIndex = 15;
			this.LabelEI.AutoSize = true;
			global::System.Windows.Forms.Control labelEI = this.LabelEI;
			location = new global::System.Drawing.Point(3, 103);
			labelEI.Location = location;
			this.LabelEI.Name = "LabelEI";
			global::System.Windows.Forms.Control labelEI2 = this.LabelEI;
			size = new global::System.Drawing.Size(37, 13);
			labelEI2.Size = size;
			this.LabelEI.TabIndex = 17;
			this.LabelEI.Text = "ERTx:";
			global::System.Windows.Forms.Control ei_TextBox = this.EI_TextBox;
			location = new global::System.Drawing.Point(42, 100);
			ei_TextBox.Location = location;
			this.EI_TextBox.Name = "EI_TextBox";
			global::System.Windows.Forms.Control ei_TextBox2 = this.EI_TextBox;
			size = new global::System.Drawing.Size(59, 20);
			ei_TextBox2.Size = size;
			this.EI_TextBox.TabIndex = 18;
			this.LabelNI.AutoSize = true;
			global::System.Windows.Forms.Control labelNI = this.LabelNI;
			location = new global::System.Drawing.Point(128, 104);
			labelNI.Location = location;
			this.LabelNI.Name = "LabelNI";
			global::System.Windows.Forms.Control labelNI2 = this.LabelNI;
			size = new global::System.Drawing.Size(38, 13);
			labelNI2.Size = size;
			this.LabelNI.TabIndex = 19;
			this.LabelNI.Text = "NRTx:";
			global::System.Windows.Forms.Control ni_TextBox = this.NI_TextBox;
			location = new global::System.Drawing.Point(167, 101);
			ni_TextBox.Location = location;
			this.NI_TextBox.Name = "NI_TextBox";
			global::System.Windows.Forms.Control ni_TextBox2 = this.NI_TextBox;
			size = new global::System.Drawing.Size(59, 20);
			ni_TextBox2.Size = size;
			this.NI_TextBox.TabIndex = 20;
			this.Label14.AutoSize = true;
			this.Label14.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label = this.Label14;
			location = new global::System.Drawing.Point(6, 9);
			label.Location = location;
			this.Label14.Name = "Label14";
			global::System.Windows.Forms.Control label2 = this.Label14;
			size = new global::System.Drawing.Size(40, 13);
			label2.Size = size;
			this.Label14.TabIndex = 0;
			this.Label14.Text = "Input:";
			global::System.Windows.Forms.Control latLonCalc_Button = this.LatLonCalc_Button;
			location = new global::System.Drawing.Point(328, 64);
			latLonCalc_Button.Location = location;
			this.LatLonCalc_Button.Name = "LatLonCalc_Button";
			global::System.Windows.Forms.Control latLonCalc_Button2 = this.LatLonCalc_Button;
			size = new global::System.Drawing.Size(50, 23);
			latLonCalc_Button2.Size = size;
			this.LatLonCalc_Button.TabIndex = 16;
			this.LatLonCalc_Button.Text = "->";
			this.LatLonCalc_Button.UseVisualStyleBackColor = true;
			global::System.Windows.Forms.Control encalc_Button = this.ENCalc_Button;
			location = new global::System.Drawing.Point(328, 99);
			encalc_Button.Location = location;
			this.ENCalc_Button.Name = "ENCalc_Button";
			global::System.Windows.Forms.Control encalc_Button2 = this.ENCalc_Button;
			size = new global::System.Drawing.Size(50, 23);
			encalc_Button2.Size = size;
			this.ENCalc_Button.TabIndex = 21;
			this.ENCalc_Button.Text = "->";
			this.ENCalc_Button.UseVisualStyleBackColor = true;
			this.Label15.AutoSize = true;
			this.Label15.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			global::System.Windows.Forms.Control label3 = this.Label15;
			location = new global::System.Drawing.Point(6, 145);
			label3.Location = location;
			this.Label15.Name = "Label15";
			global::System.Windows.Forms.Control label4 = this.Label15;
			size = new global::System.Drawing.Size(49, 13);
			label4.Size = size;
			this.Label15.TabIndex = 31;
			this.Label15.Text = "Output:";
			this.LabelLSO.AutoSize = true;
			global::System.Windows.Forms.Control labelLSO = this.LabelLSO;
			location = new global::System.Drawing.Point(16, 172);
			labelLSO.Location = location;
			this.LabelLSO.Name = "LabelLSO";
			global::System.Windows.Forms.Control labelLSO2 = this.LabelLSO;
			size = new global::System.Drawing.Size(23, 13);
			labelLSO2.Size = size;
			this.LabelLSO.TabIndex = 32;
			this.LabelLSO.Text = "LS:";
			global::System.Windows.Forms.Control lso_TextBox = this.LSO_TextBox;
			location = new global::System.Drawing.Point(55, 169);
			lso_TextBox.Location = location;
			this.LSO_TextBox.Name = "LSO_TextBox";
			this.LSO_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control lso_TextBox2 = this.LSO_TextBox;
			size = new global::System.Drawing.Size(26, 20);
			lso_TextBox2.Size = size;
			this.LSO_TextBox.TabIndex = 33;
			this.LabelMSO.AutoSize = true;
			global::System.Windows.Forms.Control labelMSO = this.LabelMSO;
			location = new global::System.Drawing.Point(88, 172);
			labelMSO.Location = location;
			this.LabelMSO.Name = "LabelMSO";
			global::System.Windows.Forms.Control labelMSO2 = this.LabelMSO;
			size = new global::System.Drawing.Size(26, 13);
			labelMSO2.Size = size;
			this.LabelMSO.TabIndex = 34;
			this.LabelMSO.Text = "MS:";
			this.LabelSSO.AutoSize = true;
			global::System.Windows.Forms.Control labelSSO = this.LabelSSO;
			location = new global::System.Drawing.Point(163, 172);
			labelSSO.Location = location;
			this.LabelSSO.Name = "LabelSSO";
			global::System.Windows.Forms.Control labelSSO2 = this.LabelSSO;
			size = new global::System.Drawing.Size(24, 13);
			labelSSO2.Size = size;
			this.LabelSSO.TabIndex = 35;
			this.LabelSSO.Text = "SS:";
			global::System.Windows.Forms.Control mso_TextBox = this.MSO_TextBox;
			location = new global::System.Drawing.Point(120, 169);
			mso_TextBox.Location = location;
			this.MSO_TextBox.Name = "MSO_TextBox";
			this.MSO_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control mso_TextBox2 = this.MSO_TextBox;
			size = new global::System.Drawing.Size(26, 20);
			mso_TextBox2.Size = size;
			this.MSO_TextBox.TabIndex = 36;
			global::System.Windows.Forms.Control sso_TextBox = this.SSO_TextBox;
			location = new global::System.Drawing.Point(193, 169);
			sso_TextBox.Location = location;
			this.SSO_TextBox.Name = "SSO_TextBox";
			this.SSO_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control sso_TextBox2 = this.SSO_TextBox;
			size = new global::System.Drawing.Size(26, 20);
			sso_TextBox2.Size = size;
			this.SSO_TextBox.TabIndex = 37;
			this.LabelXO.AutoSize = true;
			global::System.Windows.Forms.Control labelXO = this.LabelXO;
			location = new global::System.Drawing.Point(228, 172);
			labelXO.Location = location;
			this.LabelXO.Name = "LabelXO";
			global::System.Windows.Forms.Control labelXO2 = this.LabelXO;
			size = new global::System.Drawing.Size(17, 13);
			labelXO2.Size = size;
			this.LabelXO.TabIndex = 38;
			this.LabelXO.Text = "X:";
			global::System.Windows.Forms.Control xo_TextBox = this.XO_TextBox;
			location = new global::System.Drawing.Point(251, 169);
			xo_TextBox.Location = location;
			this.XO_TextBox.Name = "XO_TextBox";
			this.XO_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control xo_TextBox2 = this.XO_TextBox;
			size = new global::System.Drawing.Size(26, 20);
			xo_TextBox2.Size = size;
			this.XO_TextBox.TabIndex = 39;
			this.LabelYO.AutoSize = true;
			global::System.Windows.Forms.Control labelYO = this.LabelYO;
			location = new global::System.Drawing.Point(283, 172);
			labelYO.Location = location;
			this.LabelYO.Name = "LabelYO";
			global::System.Windows.Forms.Control labelYO2 = this.LabelYO;
			size = new global::System.Drawing.Size(17, 13);
			labelYO2.Size = size;
			this.LabelYO.TabIndex = 40;
			this.LabelYO.Text = "Y:";
			global::System.Windows.Forms.Control yo_TextBox = this.YO_TextBox;
			location = new global::System.Drawing.Point(297, 169);
			yo_TextBox.Location = location;
			this.YO_TextBox.Name = "YO_TextBox";
			this.YO_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control yo_TextBox2 = this.YO_TextBox;
			size = new global::System.Drawing.Size(26, 20);
			yo_TextBox2.Size = size;
			this.YO_TextBox.TabIndex = 41;
			this.LabelCellO.AutoSize = true;
			global::System.Windows.Forms.Control labelCellO = this.LabelCellO;
			location = new global::System.Drawing.Point(330, 172);
			labelCellO.Location = location;
			this.LabelCellO.Name = "LabelCellO";
			global::System.Windows.Forms.Control labelCellO2 = this.LabelCellO;
			size = new global::System.Drawing.Size(38, 13);
			labelCellO2.Size = size;
			this.LabelCellO.TabIndex = 42;
			this.LabelCellO.Text = "CellID:";
			global::System.Windows.Forms.Control cell0_TextBox = this.Cell0_TextBox;
			location = new global::System.Drawing.Point(364, 169);
			cell0_TextBox.Location = location;
			this.Cell0_TextBox.Name = "Cell0_TextBox";
			this.Cell0_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control cell0_TextBox2 = this.Cell0_TextBox;
			size = new global::System.Drawing.Size(64, 20);
			cell0_TextBox2.Size = size;
			this.Cell0_TextBox.TabIndex = 43;
			global::System.Windows.Forms.Control ascO_TextBox = this.AscO_TextBox;
			location = new global::System.Drawing.Point(55, 268);
			ascO_TextBox.Location = location;
			this.AscO_TextBox.Name = "AscO_TextBox";
			this.AscO_TextBox.ReadOnly = true;
			global::System.Windows.Forms.Control ascO_TextBox2 = this.AscO_TextBox;
			size = new global::System.Drawing.Size(423, 20);
			ascO_TextBox2.Size = size;
			this.AscO_TextBox.TabIndex = 44;
			this.LabelAsc.AutoSize = true;
			global::System.Windows.Forms.Control labelAsc = this.LabelAsc;
			location = new global::System.Drawing.Point(16, 271);
			labelAsc.Location = location;
			this.LabelAsc.Name = "LabelAsc";
			global::System.Windows.Forms.Control labelAsc2 = this.LabelAsc;
			size = new global::System.Drawing.Size(27, 13);
			labelAsc2.Size = size;
			this.LabelAsc.TabIndex = 45;
			this.LabelAsc.Text = "asc:";
			this.AcceptButton = this.OK_Button;
			global::System.Drawing.SizeF autoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			this.AutoScaleDimensions = autoScaleDimensions;
			this.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.Cancel_Button;
			size = new global::System.Drawing.Size(494, 361);
			this.ClientSize = size;
			this.Controls.Add(this.LabelAsc);
			this.Controls.Add(this.AscO_TextBox);
			this.Controls.Add(this.Cell0_TextBox);
			this.Controls.Add(this.LabelCellO);
			this.Controls.Add(this.YO_TextBox);
			this.Controls.Add(this.LabelYO);
			this.Controls.Add(this.XO_TextBox);
			this.Controls.Add(this.LabelXO);
			this.Controls.Add(this.SSO_TextBox);
			this.Controls.Add(this.MSO_TextBox);
			this.Controls.Add(this.LabelSSO);
			this.Controls.Add(this.LabelMSO);
			this.Controls.Add(this.LSO_TextBox);
			this.Controls.Add(this.LabelLSO);
			this.Controls.Add(this.Label15);
			this.Controls.Add(this.ENCalc_Button);
			this.Controls.Add(this.LatLonCalc_Button);
			this.Controls.Add(this.Label14);
			this.Controls.Add(this.NI_TextBox);
			this.Controls.Add(this.LabelNI);
			this.Controls.Add(this.EI_TextBox);
			this.Controls.Add(this.LabelEI);
			this.Controls.Add(this.LonI_TextBox);
			this.Controls.Add(this.Label1LonI);
			this.Controls.Add(this.LatI_TextBox);
			this.Controls.Add(this.LabelLatI);
			this.Controls.Add(this.LonO_TextBox);
			this.Controls.Add(this.LabelLonO);
			this.Controls.Add(this.LatO_TextBox);
			this.Controls.Add(this.LabelLatO);
			this.Controls.Add(this.NO_TextBox);
			this.Controls.Add(this.LabelNO);
			this.Controls.Add(this.EO_TextBox);
			this.Controls.Add(this.LabelEO);
			this.Controls.Add(this.CellCalc_Button);
			this.Controls.Add(this.YI_NumericUpDown);
			this.Controls.Add(this.LabelYI);
			this.Controls.Add(this.XI_NumericUpDown);
			this.Controls.Add(this.LabelXI);
			this.Controls.Add(this.SSI_NumericUpDown);
			this.Controls.Add(this.LabelSSI);
			this.Controls.Add(this.MSI_NumericUpDown);
			this.Controls.Add(this.LabelMSI);
			this.Controls.Add(this.LabelLSI);
			this.Controls.Add(this.LSI_NumericUpDown);
			this.Controls.Add(this.TableLayoutPanel1);
			this.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedDialog;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "CoordConvDialog";
			this.ShowInTaskbar = false;
			this.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Coordinates conversion";
			this.TableLayoutPanel1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.LSI_NumericUpDown).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.MSI_NumericUpDown).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.SSI_NumericUpDown).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.XI_NumericUpDown).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.YI_NumericUpDown).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}

		// Token: 0x0400034B RID: 843
		private global::System.ComponentModel.IContainer components;
	}
}
